# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the command line, check
# build.gradle files instead.

# When configured, Gradle will run in transitioned non-daemon mode for faster builds.
org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=512m
org.gradle.parallel=true
org.gradle.caching=true

# AndroidX package structure to make it easier to discover and migrate existing, old-style packages
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# Version numbers
compileSdk=34
targetSdk=34
minSdk=21
versionCode=1
versionName=1.0.0
